-- Find total customers by countries
Select country,
Count(customer_key) As total_customers
From gold.dim_customers
Group By country
Order By total_customers Desc

-- Find total customers by gender
Select gender,
Count(customer_key) As total_customers
From gold.dim_customers
Group By gender
Order By total_customers Desc

-- Find total products by category
Select category,
Count(product_key) As total_products
From gold.dim_products
Group By category
Order By total_products Desc

-- What is the average costs in each category?
Select category,
Avg(cost) As avg_cost
From gold.dim_products
Group By category
Order By avg_cost Desc

-- What is the total revenue generated for each category?
Select 
p.category,
Sum(f.sales_amount) total_revenue
From gold.fact_sales f
Left Join gold.dim_products p
On p.product_key = f.product_key
Group By p.category
Order By total_revenue Desc
-- Find total revenue is generated by each customer
Select 
c.customer_key,
c.first_name,
c.last_name,
Sum(f.sales_amount) total_revenue
From gold.fact_sales f
Left Join gold.dim_customers c
On c.customer_key = f.customer_key
Group By c.customer_key,
c.first_name,
c.last_name
Order By total_revenue Desc
-- What is the distribution of sold items across countries?
Select 
c.country,
Sum(f.quanity) total_sold_items
From gold.fact_sales f
Left Join gold.dim_customers c
On c.customer_key = f.customer_key
Group By c.country
Order By total_sold_items Desc